//
//  OAuthAuthorizationController.h
//  ActivityAndExpenseEntryAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"
#import "OAuthToken.h"
#import "OAuthProviderException.h"

@interface OAuthAuthorizationController : BaseController

/**
* Completion block definition for asynchronous call to request token */
typedef void (^CompletedPostRequestToken)(BOOL success, HttpContext* context, OAuthToken* response, NSError* error);

/**
* Create a new OAuth 2 token.
* @param    authorization    Required parameter: Authorization header in Basic auth format
* @param    code    Required parameter: Authorization Code
* @param    redirectUri    Required parameter: Redirect Uri
* @param    fieldParameters    Additional optional form parameters are supported by this endpoint
*/
- (void) createRequestTokenAsyncWithAuthorization:(NSString*) authorization
                code:(NSString*) code
                redirectUri:(NSString*) redirectUri
                fieldParameters:(NSDictionary*) fieldParameters
                completionBlock:(CompletedPostRequestToken) onCompleted;

/**
* Completion block definition for asynchronous call to refresh token */
typedef void (^CompletedPostRefreshToken)(BOOL success, HttpContext* context, OAuthToken* response, NSError* error);

/**
* Obtain a new access token using a refresh token
* @param    authorization    Required parameter: Authorization header in Basic auth format
* @param    refreshToken    Required parameter: Refresh token
* @param    scope    Optional parameter: Requested scopes as a space-delimited list.
* @param    fieldParameters    Additional optional form parameters are supported by this endpoint
*/
- (void) createRefreshTokenAsyncWithAuthorization:(NSString*) authorization
                refreshToken:(NSString*) refreshToken
                scope:(NSString*) scope
                fieldParameters:(NSDictionary*) fieldParameters
                completionBlock:(CompletedPostRefreshToken) onCompleted;

@end