//
//  Address.m
//  ActivityAndExpenseEntryAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#import "Address.h"

@implementation Address

/**
* TODO: Write general description for this method
*/
@synthesize name;

/**
* TODO: Write general description for this method
*/
@synthesize firstname;

/**
* TODO: Write general description for this method
*/
@synthesize lastname;

/**
* TODO: Write general description for this method
*/
@synthesize vatNumber;

/**
* TODO: Write general description for this method
*/
@synthesize street;

/**
* TODO: Write general description for this method
*/
@synthesize crossStreet;

/**
* TODO: Write general description for this method
*/
@synthesize houseNumber;

/**
* TODO: Write general description for this method
*/
@synthesize district;

/**
* TODO: Write general description for this method
*/
@synthesize postcode;

/**
* TODO: Write general description for this method
*/
@synthesize city;

/**
* TODO: Write general description for this method
*/
@synthesize state;

/**
* TODO: Write general description for this method
*/
@synthesize country;

/**
* TODO: Write general description for this method
*/
@synthesize countryCode;



/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"name": @"name",
        @"firstname": @"firstname",
        @"lastname": @"lastname",
        @"street": @"street",
        @"crossStreet": @"crossStreet",
        @"houseNumber": @"houseNumber",
        @"district": @"district",
        @"postcode": @"postcode",
        @"city": @"city",
        @"vatNumber": @"vatNumber",
        @"state": @"state",
        @"country": @"country",
        @"countryCode": @"countryCode"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end