//
//  AllowEnum.h
//  ActivityAndExpenseEntryAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_ALLOWENUMHELPER
#define APIMATIC_ALLOWENUMHELPER

#include "AllowEnum.h"

/**
* Helper class interface for AllowEnum to NSString conversion
*/
@interface AllowEnumHelper : NSObject

+(id) stringFromAllowEnum:(enum AllowEnum) allowEnum withDefault: (id) defaultValue;

+(NSArray<NSString*>*) stringArrayFromAllowEnumArray:(NSArray<NSNumber*>*) array;


+(enum AllowEnum) allowEnumFromString:(NSString*) strValue;

+(NSArray<NSNumber*>*) allowEnumArrayFromStringArray:(NSArray<NSString*>*) array;

@end

#endif