//
//  AllowEnum.h
//  ActivityAndExpenseEntryAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_ALLOWENUM
#define APIMATIC_ALLOWENUM
 
enum AllowEnum
{
        AllowNone, //TODO: Write general description for this method
        AllowAll, //TODO: Write general description for this method
};

#endif