//
//  CodeEnum.h
//  ActivityAndExpenseEntryAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_CODEENUM
#define APIMATIC_CODEENUM
 
enum CodeEnum
{
        CodeD, //TODO: Write general description for this method
        CodeH, //TODO: Write general description for this method
        CodeMin, //TODO: Write general description for this method
        CodeKm, //TODO: Write general description for this method
        CodeEnum1, //TODO: Write general description for this method
};

#endif