//
//  CombinationConstraintEntry.h
//  ActivityAndExpenseEntryAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_COMBINATIONCONSTRAINTENTRY
#define APIMATIC_COMBINATIONCONSTRAINTENTRY

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"

#import "AllowEnum.h"
#import "AllowEnumHelper.h"



//protocol defined for deserialization of JSON
@protocol CombinationConstraintEntry
@end


@interface CombinationConstraintEntry : JSONModel

/**
* base rule
*/
@property enum AllowEnum allow;
@property NSString* allowString;

/**
* exceptions to the base rule
*/
@property NSArray* except;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif
