//
//  CombinationConstraintEntry.m
//  ActivityAndExpenseEntryAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#import "CombinationConstraintEntry.h"

@implementation CombinationConstraintEntry

/**
* base rule
*/
@synthesize allow;

/**
* exceptions to the base rule
*/
@synthesize except;

 /**
 * For serialization of enum AllowEnum type property as NSString*
 */
-(id) JSONObjectForAllow
{
     
    return [AllowEnumHelper stringFromAllowEnum:(enum AllowEnum) allow withDefault: nil];

}

/**
 * For deserialization of enum AllowEnum type property from NSString*
 */
 
-(void)setAllowWithNSString:(NSString*) strValue
{
    allow = [AllowEnumHelper allowEnumFromString:(NSString*) strValue];
}




/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"allow": @"allow",
        @"except": @"except"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end