//
//  ConstraintViolation.h
//  ActivityAndExpenseEntryAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_CONSTRAINTVIOLATION
#define APIMATIC_CONSTRAINTVIOLATION

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"

#import "SeverityEnum.h"
#import "SeverityEnumHelper.h"
#import "FormattedString.h"


//protocol defined for deserialization of JSON
@protocol ConstraintViolation
@end

@interface ConstraintViolation : JSONModel

/**
* TODO: Write general description for this field
*/
@property enum SeverityEnum severity;
@property NSString<Ignore>* severityString;

/**
* TODO: Write general description for this field
*/
@property FormattedString* message;

/**
* Property name or an array index
*/
@property NSObject* propertyDescriptor;

/**
* a list of nested violations, relative to the specified property
*/
@property NSArray* violations;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif
