//
//  EntryTypeEnum.h
//  ActivityAndExpenseEntryAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#include "EntryTypeEnumHelper.h"

/**
* Helper class implementation for EntryTypeEnum to NSString conversion
*/
@implementation EntryTypeEnumHelper

+(id) stringFromEntryTypeEnum:(enum EntryTypeEnum) entryTypeEnum withDefault: (id) defaultValue
{
    switch(entryTypeEnum)
    {
        case EntryTypeActivity:
            return @"activity";

        case EntryTypeExpense:
            return @"expense";

        default:
            return defaultValue;
    }
}

+(NSArray<NSString*>*) stringArrayFromEntryTypeEnumArray:(NSArray<NSNumber*>*) array
{
    NSMutableArray* enums = [[NSMutableArray alloc]init]; 
    for(NSNumber* numberValue in array){
        NSNumber* stringValue = [EntryTypeEnumHelper stringFromEntryTypeEnum:(enum EntryTypeEnum) numberValue.intValue withDefault:[NSNull null]];
        [enums addObject:stringValue];
    }
    return [enums copy];
}

+(enum EntryTypeEnum) entryTypeEnumFromString:(NSString*) strValue
{
    NSArray* EntryTypeEnumArray = [NSArray arrayWithObjects:
                                        @"activity",
                                        @"expense",
                                        nil];

    return (enum EntryTypeEnum) [EntryTypeEnumArray indexOfObject: strValue];
}


+(NSArray<NSNumber*>*) entryTypeEnumArrayFromStringArray:(NSArray<NSString*>*) array
{
    NSMutableArray* enums = [[NSMutableArray alloc]init]; 
    for(NSString* enumValue in array){
        NSNumber* numberValue = [NSNumber numberWithInt:[ EntryTypeEnumHelper entryTypeEnumFromString:enumValue]];
        [enums addObject:numberValue];
    }
    return [enums copy];
}

@end