//
//  EntryStatusEnum.h
//  ActivityAndExpenseEntryAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_ENTRYSTATUSENUMHELPER
#define APIMATIC_ENTRYSTATUSENUMHELPER

#include "EntryStatusEnum.h"

/**
* Helper class interface for EntryStatusEnum to NSString conversion
*/
@interface EntryStatusEnumHelper : NSObject

+(id) stringFromEntryStatusEnum:(enum EntryStatusEnum) entryStatusEnum withDefault: (id) defaultValue;

+(NSArray<NSString*>*) stringArrayFromEntryStatusEnumArray:(NSArray<NSNumber*>*) array;


+(enum EntryStatusEnum) entryStatusEnumFromString:(NSString*) strValue;

+(NSArray<NSNumber*>*) entryStatusEnumArrayFromStringArray:(NSArray<NSString*>*) array;

@end

#endif