//
//  Entry.h
//  ActivityAndExpenseEntryAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_ENTRY
#define APIMATIC_ENTRY

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"

#import "EntryStatusEnum.h"
#import "EntryStatusEnumHelper.h"
#import "FormattedString.h"
#import "ConstraintViolation.h"


//protocol defined for deserialization of JSON
@protocol Entry
@end

@interface Entry : JSONModel

/**
* TODO: Write general description for this field
*/
@property NSObject* identifier;

/**
* TODO: Write general description for this field
*/
@property NSString* type;

/**
* ISO 8601:2004 date and time in UTC or with a specific offset
*/
@property NSString* creationDate;

/**
* ISO 8601:2004 date and time in UTC or with a specific offset
*/
@property NSString* modificationDate;

/**
* TODO: Write general description for this field
*/
@property enum EntryStatusEnum status;
@property NSString* statusString;

/**
* TODO: Write general description for this field
*/
@property FormattedString* statusText;

/**
* TODO: Write general description for this field
*/
@property ConstraintViolation* validationError;

/**
* TODO: Write general description for this field
*/
@property NSDictionary* userFields;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif
