//
//  EntryStatusEnum.h
//  ActivityAndExpenseEntryAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#include "EntryStatusEnumHelper.h"

/**
* Helper class implementation for EntryStatusEnum to NSString conversion
*/
@implementation EntryStatusEnumHelper

+(id) stringFromEntryStatusEnum:(enum EntryStatusEnum) entryStatusEnum withDefault: (id) defaultValue
{
    switch(entryStatusEnum)
    {
        case EntryStatusDraft:
            return @"draft";

        case EntryStatusSynchronizing:
            return @"synchronizing";

        case EntryStatusProcessing:
            return @"processing";

        case EntryStatusProcessed:
            return @"processed";

        case EntryStatusFailed:
            return @"failed";

        default:
            return defaultValue;
    }
}

+(NSArray<NSString*>*) stringArrayFromEntryStatusEnumArray:(NSArray<NSNumber*>*) array
{
    NSMutableArray* enums = [[NSMutableArray alloc]init]; 
    for(NSNumber* numberValue in array){
        NSNumber* stringValue = [EntryStatusEnumHelper stringFromEntryStatusEnum:(enum EntryStatusEnum) numberValue.intValue withDefault:[NSNull null]];
        [enums addObject:stringValue];
    }
    return [enums copy];
}

+(enum EntryStatusEnum) entryStatusEnumFromString:(NSString*) strValue
{
    NSArray* EntryStatusEnumArray = [NSArray arrayWithObjects:
                                        @"draft",
                                        @"synchronizing",
                                        @"processing",
                                        @"processed",
                                        @"failed",
                                        nil];

    return (enum EntryStatusEnum) [EntryStatusEnumArray indexOfObject: strValue];
}


+(NSArray<NSNumber*>*) entryStatusEnumArrayFromStringArray:(NSArray<NSString*>*) array
{
    NSMutableArray* enums = [[NSMutableArray alloc]init]; 
    for(NSString* enumValue in array){
        NSNumber* numberValue = [NSNumber numberWithInt:[ EntryStatusEnumHelper entryStatusEnumFromString:enumValue]];
        [enums addObject:numberValue];
    }
    return [enums copy];
}

@end