//
//  EntryTypeEnum.h
//  ActivityAndExpenseEntryAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_ENTRYTYPEENUMHELPER
#define APIMATIC_ENTRYTYPEENUMHELPER

#include "EntryTypeEnum.h"

/**
* Helper class interface for EntryTypeEnum to NSString conversion
*/
@interface EntryTypeEnumHelper : NSObject

+(id) stringFromEntryTypeEnum:(enum EntryTypeEnum) entryTypeEnum withDefault: (id) defaultValue;

+(NSArray<NSString*>*) stringArrayFromEntryTypeEnumArray:(NSArray<NSNumber*>*) array;


+(enum EntryTypeEnum) entryTypeEnumFromString:(NSString*) strValue;

+(NSArray<NSNumber*>*) entryTypeEnumArrayFromStringArray:(NSArray<NSString*>*) array;

@end

#endif