//
//  EntryStatusEnum.h
//  ActivityAndExpenseEntryAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_ENTRYSTATUSENUM
#define APIMATIC_ENTRYSTATUSENUM
 
enum EntryStatusEnum
{
        EntryStatusDraft, //TODO: Write general description for this method
        EntryStatusSynchronizing, //TODO: Write general description for this method
        EntryStatusProcessing, //TODO: Write general description for this method
        EntryStatusProcessed, //TODO: Write general description for this method
        EntryStatusFailed, //TODO: Write general description for this method
};

#endif