//
//  EntryTypeEnum.h
//  ActivityAndExpenseEntryAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_ENTRYTYPEENUM
#define APIMATIC_ENTRYTYPEENUM
 
enum EntryTypeEnum
{
        EntryTypeActivity, //TODO: Write general description for this method
        EntryTypeExpense, //TODO: Write general description for this method
};

#endif