//
//  EnumerationTypeEnum.h
//  ActivityAndExpenseEntryAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_ENUMERATIONTYPEENUM
#define APIMATIC_ENUMERATIONTYPEENUM
 
enum EnumerationTypeEnum
{
        EnumerationTypeProject, //TODO: Write general description for this method
        EnumerationTypeWorkPackage, //TODO: Write general description for this method
        EnumerationTypeServiceCode, //TODO: Write general description for this method
        EnumerationTypeAbsenceType, //TODO: Write general description for this method
        EnumerationTypeExpenseType, //TODO: Write general description for this method
        EnumerationTypeUserfieldDefinition, //TODO: Write general description for this method
        EnumerationTypeCurrency, //TODO: Write general description for this method
};

#endif