//
//  Enumerator.m
//  ActivityAndExpenseEntryAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#import "Enumerator.h"

@implementation Enumerator

/**
* TODO: Write general description for this method
*/
@synthesize mid;

/**
* TODO: Write general description for this method
*/
@synthesize label;

/**
* TODO: Write general description for this method
*/
@synthesize customId;

/**
* TODO: Write general description for this method
*/
@synthesize type;

/**
* TODO: Write general description for this method
*/
@synthesize secondaryLabel;

/**
* TODO: Write general description for this method
*/
@synthesize categoryLabel;



/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"id": @"mid",
        @"label": @"label",
        @"customId": @"customId",
        @"type": @"type",
        @"secondaryLabel": @"secondaryLabel",
        @"categoryLabel": @"categoryLabel"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end