//
//  EnumerationTypeEnum.h
//  ActivityAndExpenseEntryAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_ENUMERATIONTYPEENUMHELPER
#define APIMATIC_ENUMERATIONTYPEENUMHELPER

#include "EnumerationTypeEnum.h"

/**
* Helper class interface for EnumerationTypeEnum to NSString conversion
*/
@interface EnumerationTypeEnumHelper : NSObject

+(id) stringFromEnumerationTypeEnum:(enum EnumerationTypeEnum) enumerationTypeEnum withDefault: (id) defaultValue;

+(NSArray<NSString*>*) stringArrayFromEnumerationTypeEnumArray:(NSArray<NSNumber*>*) array;


+(enum EnumerationTypeEnum) enumerationTypeEnumFromString:(NSString*) strValue;

+(NSArray<NSNumber*>*) enumerationTypeEnumArrayFromStringArray:(NSArray<NSString*>*) array;

@end

#endif