//
//  EnumerationTypeEnum.h
//  ActivityAndExpenseEntryAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#include "EnumerationTypeEnumHelper.h"

/**
* Helper class implementation for EnumerationTypeEnum to NSString conversion
*/
@implementation EnumerationTypeEnumHelper

+(id) stringFromEnumerationTypeEnum:(enum EnumerationTypeEnum) enumerationTypeEnum withDefault: (id) defaultValue
{
    switch(enumerationTypeEnum)
    {
        case EnumerationTypeProject:
            return @"project";

        case EnumerationTypeWorkPackage:
            return @"work_package";

        case EnumerationTypeServiceCode:
            return @"service_code";

        case EnumerationTypeAbsenceType:
            return @"absence_type";

        case EnumerationTypeExpenseType:
            return @"expense_type";

        case EnumerationTypeUserfieldDefinition:
            return @"userfield_definition";

        case EnumerationTypeCurrency:
            return @"currency";

        default:
            return defaultValue;
    }
}

+(NSArray<NSString*>*) stringArrayFromEnumerationTypeEnumArray:(NSArray<NSNumber*>*) array
{
    NSMutableArray* enums = [[NSMutableArray alloc]init]; 
    for(NSNumber* numberValue in array){
        NSNumber* stringValue = [EnumerationTypeEnumHelper stringFromEnumerationTypeEnum:(enum EnumerationTypeEnum) numberValue.intValue withDefault:[NSNull null]];
        [enums addObject:stringValue];
    }
    return [enums copy];
}

+(enum EnumerationTypeEnum) enumerationTypeEnumFromString:(NSString*) strValue
{
    NSArray* EnumerationTypeEnumArray = [NSArray arrayWithObjects:
                                        @"project",
                                        @"work_package",
                                        @"service_code",
                                        @"absence_type",
                                        @"expense_type",
                                        @"userfield_definition",
                                        @"currency",
                                        nil];

    return (enum EnumerationTypeEnum) [EnumerationTypeEnumArray indexOfObject: strValue];
}


+(NSArray<NSNumber*>*) enumerationTypeEnumArrayFromStringArray:(NSArray<NSString*>*) array
{
    NSMutableArray* enums = [[NSMutableArray alloc]init]; 
    for(NSString* enumValue in array){
        NSNumber* numberValue = [NSNumber numberWithInt:[ EnumerationTypeEnumHelper enumerationTypeEnumFromString:enumValue]];
        [enums addObject:numberValue];
    }
    return [enums copy];
}

@end