//
//  Expense.h
//  ActivityAndExpenseEntryAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_EXPENSE
#define APIMATIC_EXPENSE

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"

#import "Entry.h"
#import "Unit.h"
#import "Location.h"
#import "Attachment.h"


//protocol defined for deserialization of JSON
@protocol Expense
@end

@interface Expense : Entry

/**
* ISO 8601:2004 date and time in UTC or with a specific offset
*/
@property NSString* date;

/**
* TODO: Write general description for this field
*/
@property NSNumber* quantity;

/**
* A subset of UCUM codes with a descriptive name.
* UCUM Specification: http://unitsofmeasure.org/ucum.html
*/
@property Unit* unit;

/**
* TODO: Write general description for this field
*/
@property NSNumber* amount;

/**
* TODO: Write general description for this field
*/
@property NSString* currency;

/**
* TODO: Write general description for this field
*/
@property NSString* creditCard;

/**
* TODO: Write general description for this field
*/
@property NSString* project;

/**
* TODO: Write general description for this field
*/
@property NSString* workPackage;

/**
* TODO: Write general description for this field
*/
@property NSString* expenseType;

/**
* TODO: Write general description for this field
*/
@property Location* location;

/**
* TODO: Write general description for this field
*/
@property NSString* comment;

/**
* TODO: Write general description for this field
*/
@property NSString* internalComment;

/**
* TODO: Write general description for this field
*/
@property NSString* externalComment;

/**
* TODO: Write general description for this field
*/
@property NSArray<Attachment> * attachments;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif