//
//  FormatEnum.h
//  ActivityAndExpenseEntryAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_FORMATENUM
#define APIMATIC_FORMATENUM
 
enum FormatEnum
{
        FormatDatetime, //TODO: Write general description for this method
        FormatDate, //TODO: Write general description for this method
        FormatTime, //TODO: Write general description for this method
};

#endif