//
//  FormattedString.h
//  ActivityAndExpenseEntryAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_FORMATTEDSTRING
#define APIMATIC_FORMATTEDSTRING

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol FormattedString
@end

@interface FormattedString : JSONModel

/**
* untranslated default format string, which must take all arguments provided in formatStringArgs, if any
*/
@property NSString* defaultFormatString;

/**
* global identifier for a translatable format string
*/
@property NSNumber* formatStringId;

/**
* format string args for defaultFormatString or the format string identified by formatStringId
*/
@property NSArray* formatStringArgs;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif