//
//  FormatEnum.h
//  ActivityAndExpenseEntryAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_FORMATENUMHELPER
#define APIMATIC_FORMATENUMHELPER

#include "FormatEnum.h"

/**
* Helper class interface for FormatEnum to NSString conversion
*/
@interface FormatEnumHelper : NSObject

+(id) stringFromFormatEnum:(enum FormatEnum) formatEnum withDefault: (id) defaultValue;

+(NSArray<NSString*>*) stringArrayFromFormatEnumArray:(NSArray<NSNumber*>*) array;


+(enum FormatEnum) formatEnumFromString:(NSString*) strValue;

+(NSArray<NSNumber*>*) formatEnumArrayFromStringArray:(NSArray<NSString*>*) array;

@end

#endif