//
//  InputFormatEnum.h
//  ActivityAndExpenseEntryAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_INPUTFORMATENUMHELPER
#define APIMATIC_INPUTFORMATENUMHELPER

#include "InputFormatEnum.h"

/**
* Helper class interface for InputFormatEnum to NSString conversion
*/
@interface InputFormatEnumHelper : NSObject

+(id) stringFromInputFormatEnum:(enum InputFormatEnum) inputFormatEnum withDefault: (id) defaultValue;

+(NSArray<NSString*>*) stringArrayFromInputFormatEnumArray:(NSArray<NSNumber*>*) array;


+(enum InputFormatEnum) inputFormatEnumFromString:(NSString*) strValue;

+(NSArray<NSNumber*>*) inputFormatEnumArrayFromStringArray:(NSArray<NSString*>*) array;

@end

#endif