//
//  InputFormatEnum.h
//  ActivityAndExpenseEntryAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_INPUTFORMATENUM
#define APIMATIC_INPUTFORMATENUM
 
enum InputFormatEnum
{
        InputFormatSCALAR, //TODO: Write general description for this method
        InputFormatRANGE, //TODO: Write general description for this method
};

#endif