//
//  Location.m
//  ActivityAndExpenseEntryAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#import "Location.h"

@implementation Location

/**
* TODO: Write general description for this method
*/
@synthesize latitude;

/**
* TODO: Write general description for this method
*/
@synthesize longitude;

/**
* TODO: Write general description for this method
*/
@synthesize name;

/**
* TODO: Write general description for this method
*/
@synthesize premise;

/**
* TODO: Write general description for this method
*/
@synthesize subpremise;

/**
* TODO: Write general description for this method
*/
@synthesize address;



/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"latitude": @"latitude",
        @"longitude": @"longitude",
        @"name": @"name",
        @"premise": @"premise",
        @"subpremise": @"subpremise",
        @"address": @"address"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end