//
//  Location.h
//  ActivityAndExpenseEntryAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_LOCATION
#define APIMATIC_LOCATION

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"

#import "Address.h"


//protocol defined for deserialization of JSON
@protocol Location
@end

@interface Location : JSONModel

/**
* TODO: Write general description for this field
*/
@property NSNumber* latitude;

/**
* TODO: Write general description for this field
*/
@property NSNumber* longitude;

/**
* TODO: Write general description for this field
*/
@property NSString* name;

/**
* TODO: Write general description for this field
*/
@property NSString* premise;

/**
* TODO: Write general description for this field
*/
@property NSString* subpremise;

/**
* TODO: Write general description for this field
*/
@property Address* address;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif