//
//  OAuthProviderException.h
//  ActivityAndExpenseEntryAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#import <Foundation/Foundation.h>
#import "APIError.h"
#import "HttpContext.h"
#import "OAuthProviderErrorEnum.h"
#import "OAuthProviderErrorEnumHelper.h"



@interface OAuthProviderException : APIError
 
 /**
* Error code
*/
@property enum OAuthProviderErrorEnum error;

/**
* Human-readable text providing additional information on error.
* Used to assist the client developer in understanding the error that occurred.
*/
@property NSString* errorDescription;

/**
* A URI identifying a human-readable web page with information about the error, used to provide the client developer with additional information about the error
*/
@property NSString* errorUri;

- (OAuthProviderException*) initWithReason: (NSString*) reason
                                  andContext: (HttpContext*) context;

@end