//
//  OAuthProviderErrorEnum.h
//  ActivityAndExpenseEntryAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_OAUTHPROVIDERERRORENUM
#define APIMATIC_OAUTHPROVIDERERRORENUM
 
enum OAuthProviderErrorEnum
{
        OAuthProviderErrorInvalidRequest, //The request is missing a required parameter, includes an unsupported parameter value (other than grant type), repeats a parameter, includes multiple credentials, utilizes more than one mechanism for authenticating the client, or is otherwise malformed.
        OAuthProviderErrorInvalidClient, //Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method).
        OAuthProviderErrorInvalidGrant, //The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.
        OAuthProviderErrorUnauthorizedClient, //The authenticated client is not authorized to use this authorization grant type.
        OAuthProviderErrorUnsupportedGrantType, //The authorization grant type is not supported by the authorization server.
        OAuthProviderErrorInvalidScope, //The requested scope is invalid, unknown, malformed, or exceeds the scope granted by the resource owner.
};

#endif