//
//  OAuthScopeEnum.h
//  ActivityAndExpenseEntryAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_OAUTHSCOPEENUM
#define APIMATIC_OAUTHSCOPEENUM
 
enum OAuthScopeEnum
{
        OAuthScopeAbacusPad, //Access to the Pad API (AbaClik 1)
        OAuthScopeAbacusClient7777, //Mandant 7777 (AbaClik 2)
        OAuthScopeOfflineAccess, //unattended access
};

#endif