//
//  OAuthToken.h
//  ActivityAndExpenseEntryAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_OAUTHTOKEN
#define APIMATIC_OAUTHTOKEN

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol OAuthToken
@end

@interface OAuthToken : JSONModel

/**
* Access token
*/
@property NSString* accessToken;

/**
* Type of access token
*/
@property NSString* tokenType;

/**
* Time in seconds before the access token expires
*/
@property NSNumber* expiresIn;

/**
* List of scopes granted
* This is a space-delimited list of strings.
*/
@property NSString* scope;

/**
* Time of token expiry as unix timestamp (UTC)
*/
@property NSNumber* expiry;

/**
* Refresh token
* Used to get a new access token when it expires.
*/
@property NSString* refreshToken;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif