//
//  OAuthProviderErrorEnum.h
//  ActivityAndExpenseEntryAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_OAUTHPROVIDERERRORENUMHELPER
#define APIMATIC_OAUTHPROVIDERERRORENUMHELPER

#include "OAuthProviderErrorEnum.h"

/**
* Helper class interface for OAuthProviderErrorEnum to NSString conversion
*/
@interface OAuthProviderErrorEnumHelper : NSObject

+(id) stringFromOAuthProviderErrorEnum:(enum OAuthProviderErrorEnum) oAuthProviderErrorEnum withDefault: (id) defaultValue;

+(NSArray<NSString*>*) stringArrayFromOAuthProviderErrorEnumArray:(NSArray<NSNumber*>*) array;


+(enum OAuthProviderErrorEnum) oAuthProviderErrorEnumFromString:(NSString*) strValue;

+(NSArray<NSNumber*>*) oAuthProviderErrorEnumArrayFromStringArray:(NSArray<NSString*>*) array;

@end

#endif