//
//  OAuthToken.m
//  ActivityAndExpenseEntryAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#import "OAuthToken.h"

@implementation OAuthToken

/**
* Access token
*/
@synthesize accessToken;

/**
* Type of access token
*/
@synthesize tokenType;

/**
* Time in seconds before the access token expires
*/
@synthesize expiresIn;

/**
* List of scopes granted
* This is a space-delimited list of strings.
*/
@synthesize scope;

/**
* Time of token expiry as unix timestamp (UTC)
*/
@synthesize expiry;

/**
* Refresh token
* Used to get a new access token when it expires.
*/
@synthesize refreshToken;



/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"access_token": @"accessToken",
        @"token_type": @"tokenType",
        @"expires_in": @"expiresIn",
        @"scope": @"scope",
        @"expiry": @"expiry",
        @"refresh_token": @"refreshToken"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end