
#import "ProblemDetailsException.h"
@implementation ProblemDetailsException

/**
* An absolute URI [RFC3986] that identifies the
* problem type. When dereferenced, it SHOULD provide human-readable
* documentation for the problem type (e.g., using HTML
* [W3C.REC-html401-19991224]). When this member is not present, its
* value is assumed to be "about:blank".
*/
@synthesize type;

/**
* A short, human-readable summary of the problem
* type. It SHOULD NOT change from occurrence to occurrence of the
* problem, except for purposes of localisation.
*/
@synthesize title;

/**
* The HTTP status code ([RFC2616], Section 6)
* generated by the origin server for this occurrence of the problem.
*/
@synthesize status;

/**
* An human readable explanation specific to this
* occurrence of the problem.
*/
@synthesize detail;

/**
* An absolute URI that identifies the specific
* occurrence of the problem. It may or may not yield further
* information if dereferenced.
*/
@synthesize instance;


- (ProblemDetailsException*) initWithReason: (NSString*) reason
                                  andContext: (HttpContext*) context
{
    self = [super initWithReason:reason andContext:context];
    return self;
}

- (void) unbox
{
    NSDictionary* data = [APIHelper jsonDeserializeObject: self.context.response.rawBody];
    type = [data objectForKey: @"type"];
    title = [data objectForKey: @"title"];
    status = [NSNumber numberWithInteger:[[data objectForKey: @"status"] integerValue]];
    detail = [data objectForKey: @"detail"];
    instance = [data objectForKey: @"instance"];
}
@end