//
//  ProblemDetailsException.h
//  ActivityAndExpenseEntryAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#import <Foundation/Foundation.h>
#import "APIError.h"
#import "HttpContext.h"



@interface ProblemDetailsException : APIError
 
 /**
* An absolute URI [RFC3986] that identifies the
* problem type. When dereferenced, it SHOULD provide human-readable
* documentation for the problem type (e.g., using HTML
* [W3C.REC-html401-19991224]). When this member is not present, its
* value is assumed to be "about:blank".
*/
@property NSString* type;

/**
* A short, human-readable summary of the problem
* type. It SHOULD NOT change from occurrence to occurrence of the
* problem, except for purposes of localisation.
*/
@property NSString* title;

/**
* The HTTP status code ([RFC2616], Section 6)
* generated by the origin server for this occurrence of the problem.
*/
@property NSNumber* status;

/**
* An human readable explanation specific to this
* occurrence of the problem.
*/
@property NSString* detail;

/**
* An absolute URI that identifies the specific
* occurrence of the problem. It may or may not yield further
* information if dereferenced.
*/
@property NSString* instance;

- (ProblemDetailsException*) initWithReason: (NSString*) reason
                                  andContext: (HttpContext*) context;

@end