//
//  ProblemDetails167.h
//  ActivityAndExpenseEntryAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_PROBLEMDETAILS167
#define APIMATIC_PROBLEMDETAILS167

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol ProblemDetails167
@end

@interface ProblemDetails167 : JSONModel

/**
* An absolute URI [RFC3986] that identifies the
* problem type. When dereferenced, it SHOULD provide human-readable
* documentation for the problem type (e.g., using HTML
* [W3C.REC-html401-19991224]). When this member is not present, its
* value is assumed to be "about:blank".
*/
@property NSString* type;

/**
* A short, human-readable summary of the problem
* type. It SHOULD NOT change from occurrence to occurrence of the
* problem, except for purposes of localisation.
*/
@property NSString* title;

/**
* The HTTP status code ([RFC2616], Section 6)
* generated by the origin server for this occurrence of the problem.
*/
@property NSNumber* status;

/**
* An human readable explanation specific to this
* occurrence of the problem.
*/
@property NSString* detail;

/**
* An absolute URI that identifies the specific
* occurrence of the problem. It may or may not yield further
* information if dereferenced.
*/
@property NSString* instance;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif