//
//  SeverityEnum.h
//  ActivityAndExpenseEntryAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#include "SeverityEnumHelper.h"

/**
* Helper class implementation for SeverityEnum to NSString conversion
*/
@implementation SeverityEnumHelper

+(id) stringFromSeverityEnum:(enum SeverityEnum) severityEnum withDefault: (id) defaultValue
{
    switch(severityEnum)
    {
        case SeverityINFO:
            return @"INFO";

        case SeverityWARNING:
            return @"WARNING";

        case SeverityERROR:
            return @"ERROR";

        default:
            return defaultValue;
    }
}

+(NSArray<NSString*>*) stringArrayFromSeverityEnumArray:(NSArray<NSNumber*>*) array
{
    NSMutableArray* enums = [[NSMutableArray alloc]init]; 
    for(NSNumber* numberValue in array){
        NSNumber* stringValue = [SeverityEnumHelper stringFromSeverityEnum:(enum SeverityEnum) numberValue.intValue withDefault:[NSNull null]];
        [enums addObject:stringValue];
    }
    return [enums copy];
}

+(enum SeverityEnum) severityEnumFromString:(NSString*) strValue
{
    NSArray* SeverityEnumArray = [NSArray arrayWithObjects:
                                        @"INFO",
                                        @"WARNING",
                                        @"ERROR",
                                        nil];

    return (enum SeverityEnum) [SeverityEnumArray indexOfObject: strValue];
}


+(NSArray<NSNumber*>*) severityEnumArrayFromStringArray:(NSArray<NSString*>*) array
{
    NSMutableArray* enums = [[NSMutableArray alloc]init]; 
    for(NSString* enumValue in array){
        NSNumber* numberValue = [NSNumber numberWithInt:[ SeverityEnumHelper severityEnumFromString:enumValue]];
        [enums addObject:numberValue];
    }
    return [enums copy];
}

@end