//
//  SeverityEnum.h
//  ActivityAndExpenseEntryAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_SEVERITYENUMHELPER
#define APIMATIC_SEVERITYENUMHELPER

#include "SeverityEnum.h"

/**
* Helper class interface for SeverityEnum to NSString conversion
*/
@interface SeverityEnumHelper : NSObject

+(id) stringFromSeverityEnum:(enum SeverityEnum) severityEnum withDefault: (id) defaultValue;

+(NSArray<NSString*>*) stringArrayFromSeverityEnumArray:(NSArray<NSNumber*>*) array;


+(enum SeverityEnum) severityEnumFromString:(NSString*) strValue;

+(NSArray<NSNumber*>*) severityEnumArrayFromStringArray:(NSArray<NSString*>*) array;

@end

#endif