//
//  SeverityEnum.h
//  ActivityAndExpenseEntryAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_SEVERITYENUM
#define APIMATIC_SEVERITYENUM
 
enum SeverityEnum
{
        SeverityINFO, //TODO: Write general description for this method
        SeverityWARNING, //TODO: Write general description for this method
        SeverityERROR, //TODO: Write general description for this method
};

#endif