//
//  SubTypeEnum.h
//  ActivityAndExpenseEntryAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_SUBTYPEENUM
#define APIMATIC_SUBTYPEENUM

enum SubTypeEnum
{
  SubTypeVacation,
  SubTypeSickness,
  SubTypeMilitary,
  SubTypeAccident,
  SubTypeEducation,
  SubTypeOther,
};

#endif
