//
//  SubTypeEnum.h
//  ActivityAndExpenseEntryAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_SUBTYPEENUM
#define APIMATIC_SUBTYPEENUM
 
enum SubTypeEnum
{
        SubTypePause, //TODO: Write general description for this method
        SubTypeVacation, //TODO: Write general description for this method
        SubTypeCompensation, //TODO: Write general description for this method
};

#endif