//
//  TypeEnum.h
//  ActivityAndExpenseEntryAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_TYPEENUM
#define APIMATIC_TYPEENUM
 
enum TypeEnum
{
        TypeObject, //TODO: Write general description for this method
        TypeArray, //TODO: Write general description for this method
        TypeString, //TODO: Write general description for this method
        TypeBoolean, //TODO: Write general description for this method
        TypeNumber, //TODO: Write general description for this method
        TypeNull, //TODO: Write general description for this method
};

#endif