//
//  Unit.h
//  ActivityAndExpenseEntryAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_UNIT
#define APIMATIC_UNIT

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"

#import "CodeEnum.h"
#import "CodeEnumHelper.h"


//protocol defined for deserialization of JSON
@protocol Unit
@end

@interface Unit : JSONModel

/**
* The ucum code.
* See following sections in the UCUM specification:
* * TABLES OF TERMINAL SYMBOLS / PREFIXES
* * TABLES OF TERMINAL SYMBOLS / BASE UNITS
* * EXAMPLES FOR SOME NON-UNITS
*/
@property enum CodeEnum code;
@property NSString<Ignore>* codeString;

/**
* TODO: Write general description for this field
*/
@property NSString* descriptiveName;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif
